eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Accountteam
          uri: http://localhost:9000
          predicates:
            - Path=/accounts/**
        - id: adminservice
          uri: http://localhost:9001
          predicates:
            - Path=/admin/**